### ISSUE TITLE
Cobblestone Generators

### ISSUE THREAD

**Issue by Zak223** [Zak223/Greggic-Skies#16]
Tiny Progression cobblestone generators

- [x] Tier one - Block of Iron
- [ ] Tier two - LV Circuit
- [ ] Tier three - MV Circuit
- [ ] Tier four - HV Circuit
- [ ] Tier five - EV Circuit

These gates are to help keep up with the voltage tiers' needs for materials, and to bring some gating into Tiny Progressions

**Comment by myutin** [comment]
Rock breakers (cobble generators) already exist in GTCEu, and are well-balanced in my opinion. See default recipes here:
https://github.com/GregTechCEu/GregTech/blob/master/src/main/java/gregtech/loaders/recipe/MiscRecipeLoader.java
TP's cobble gens seem to be 25% slower at each tier, but require no power, and can't make other stone variants. Consider removing the TP cobble gens entirely, for a more greggy experience.

**Comment by Zak223** [comment]
> Rock breakers (cobble generators) already exist in GTCEu, and are well-balanced in my opinion. See default recipes here: https://github.com/GregTechCEu/GregTech/blob/master/src/main/java/gregtech/loaders/recipe/MiscRecipeLoader.java TP's cobble gens seem to be 25% slower at each tier, but require no power, and can't make other stone variants. Consider removing the TP cobble gens entirely, for a more greggy experience.

In all honesty I forgot about these, I will get rid of the TP cobble gens and stick with the gregtech versions
